openapi: 3.0.0
info:
  title: Placeholderimage generator API
  description: Just for learning fun.
  version: 0.0.8
servers:
  - url: http://localhost:8000
    description: Optional server description is not truly available
paths:
  /placeholder:
    get:
      summary: returns a 1px grey png
      description: You can use this to create a 1x1 Pixel sized placeholder that you can strech with width and height attributes. <img src="http://localhost:8000/placeholder" width=200 height=100>
  /{extension}/{width}x{height}:
    get:
      summary: returns a image with the given extension, the width and height
      description: with /png/200x100/ you get a small png that you can resize in side your HTML with <img src=http://localhost:8000/png/200x100/>
      parameters:
        - name: extension
          in: path
          required: true
          description: Generates a image with the requested mime-type. E. g. jpg, jpeg, png, ...
          schema:
            type : string
            minimum: 3
            maximum: 4
            example: png
        - name: width
          in: path
          required: true
          description: Generates a image with desired width in pixel
          schema:
            type : integer
            minimum: 1
            maximum: 9999
            example: 1
        - name: height
          in: path
          required: true
          description: Generates a image with desired height in pixel
          schema:
            type : integer
            minimum: 1
            maximum: 9999
            example: 1
            
  /{extension}/{width}x{height}/{backgroundColor}:
    get:
      summary: returns a image with the given extension, the width and height
      description: with /png/10x10/cccccc you get a 10px square png, with a gray background. The text-color will be choosen by the contrast to the wished backgroundColor
      parameters:
        - name: extension
          in: path
          required: true
          description: Generates a image with the requested mime-type. E. g. jpg, jpeg, png, ...
          schema:
            type : string
            minimum: 3
            maximum: 4
            example: png
        - name: width
          in: path
          required: true
          description: Generates a image with desired width in pixel
          schema:
            type : integer
            minimum: 1
            maximum: 9999
            example: 1
        - name: height
          in: path
          required: true
          description: Generates a image with desired height in pixel
          schema:
            type : integer
            minimum: 1
            maximum: 9999
            example: 1
        - name: backgroundColor
          in: path
          required: false
          description: Generates a image with desired background color.If this parameter is not send, a default color will be used
          schema:
            type : string
            length: 6
            example: 666666
      responses:
        '200':    # status code