openapi: 3.0.0
info:
  title: Placeholder Image Service API
  description: Just for learning fun.
  version: 0.0.8
servers:
  - url: http://localhost:8000
    description: Optional server description is not truly available
paths:
  /placeholder:
    get:
      summary: Returns a 1px grey png
      description: You can use this to create a 1x1 Pixel sized placeholder that you can strech with width and height attributes. <img src="http://localhost:8000/placeholder" width=200 height=100>
      responses:
        '200':
          description: An image
  /{extension}/{width}x{height}:
    get:
      summary: Returns a image with the given extension, the width and height
      description: With /jpg/200x100/ you get a 200x100 png in gray <img src=http://localhost:8000/jpg/200x100/>
      parameters:
        - name: extension
          in: path
          required: true
          description: Generates a image with the requested mime-type. E. g. jpg, jpeg, png, ...
          schema:
            type : string
            minimum: 3
            maximum: 4
            example: png
        - name: width
          in: path
          required: true
          description: Generates a image with desired width in pixel
          schema:
            type : integer
            minimum: 1
            maximum: 9999
            example: 400
        - name: height
          in: path
          required: true
          description: Generates a image with desired height in pixel
          schema:
            type : integer
            minimum: 1
            maximum: 9999
            example: 200
      responses:
        '200':
          description: An image
  /{extension}/{width}x{height}/color/{color}:
    get:
      summary: Returns a image with the given extension, the width and height
      description: With /png/100x100/color/ff0000 you get a 100px square png, with a red background. The text-color will be choosen by the contrast to the wished color. Example output <img src=http://localhost:8000/png/100x100/color/ff0000>
      parameters:
        - name: extension
          in: path
          required: true
          description: Generates a image with the requested mime-type. E. g. jpg, jpeg, png, ...
          schema:
            type : string
            minimum: 3
            maximum: 4
            example: png
        - name: width
          in: path
          required: true
          description: Generates a image with desired width in pixel
          schema:
            type : integer
            minimum: 1
            maximum: 9999
            example: 400
        - name: height
          in: path
          required: true
          description: Generates a image with desired height in pixel
          schema:
            type : integer
            minimum: 1
            maximum: 9999
            example: 200
        - name: color
          in: path
          required: true
          description: Generates a image with desired background color.If this parameter is not send, a default color will be used
          schema:
            type : string
            minLength: 6
            maxLength: 6
            example: 9900ff
      responses:
        '200':
          description: An image
  /{extension}/{width}x{height}/search/{queryString}:
    get:
      summary: Search for an image at pixabay with the queryString parameter and creates a placholder image with the disred dimensions
      description: With /png/250x200/search/elephant you get a 250x200 pixel photo with the keywords "elephant". . Example output <img src=http://localhost:8000/png/250x200/search/elephant>
      parameters:
        - name: extension
          in: path
          required: true
          description: Generates a image with the requested mime-type. E. g. jpg, jpeg, png, ...
          schema:
            type : string
            minimum: 3
            maximum: 4
            example: png
        - name: width
          in: path
          required: true
          description: Generates a image with desired width in pixel
          schema:
            type : integer
            minimum: 1
            maximum: 9999
            example: 480
        - name: height
          in: path
          required: true
          description: Generates a image with desired height in pixel
          schema:
            type : integer
            minimum: 1
            maximum: 9999
            example: 360
        - name: queryString
          in: path
          required: true
          description: this parameter hold the search query against the pixabay api
          schema:
            type : string
            minLength: 1
            maxLength: 40
            example: nature
      responses:
        '200':
          description: An image